---
- name: Create a network with custom IPAM config
  community.docker.docker_network:
    name: network_dc
    ipam_config:
      - subnet: 172.23.27.0/24
  tags:
    - start

- name: Delete a network, disconnecting all containers
  community.docker.docker_network:
    name: network_dc
    state: absent
    force: yes


- name: Start 4 load-balanced containers
  community.docker.docker_container:
    name: "container{{ item }}"
    recreate: yes
    image: ubuntubase:latest
    networks:
      - name: network_dc
        ipv4_address: "172.23.27.{{ item+1 }}"
  with_sequence: count=4
  tags:
    - start

- name: Remove container
  community.docker.docker_container:
    name: "container{{ item }}"
    state: absent
  with_sequence: count=4
  tags:
    - stop
