---
- name: Create custom whitelist groups
  include: whitelist.yaml
  when: squid_custom_whitelist is defined and squid_custom_whitelist

- name: install squid
  package: name={{ squid_package }} state=present update_cache=yes

- name: copy template
  template: src=squid.conf.j2 dest={{ squid_conf }} owner=root group=root mode=0644
  notify: restart squid